/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineIdStringCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineIdStringCollection (0 custom class methods, 1 custom properties)

#import "GTLFlagengineIdStringCollection.h"

#import "GTLFlagengineIdString.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineIdStringCollection
//

@implementation GTLFlagengineIdStringCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLFlagengineIdString class]
                                forKey:@"items"];
  return map;
}

@end
