/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineIdString.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineIdString (0 custom class methods, 3 custom properties)

#import "GTLFlagengineIdString.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineIdString
//

@implementation GTLFlagengineIdString
@dynamic identifier, statusCode, string;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
