/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineUploadUrl.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineUploadUrl (0 custom class methods, 1 custom properties)

#import "GTLFlagengineUploadUrl.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineUploadUrl
//

@implementation GTLFlagengineUploadUrl
@dynamic url;
@end
