/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineBranchItemMatcher.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineBranchItemMatcher (0 custom class methods, 5 custom properties)

#import "GTLFlagengineBranchItemMatcher.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineBranchItemMatcher
//

@implementation GTLFlagengineBranchItemMatcher
@dynamic branchShopId, identifier, itemId, rewardable, statusCode;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
