/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineProvider.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineProvider (0 custom class methods, 4 custom properties)

#import "GTLFlagengineProvider.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineProvider
//

@implementation GTLFlagengineProvider
@dynamic balance, email, identifier, password;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
