/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineFlag.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineFlag (0 custom class methods, 10 custom properties)

#import "GTLFlagengineFlag.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineFlag
//

@implementation GTLFlagengineFlag
@dynamic createdAt, distance, identifier, lat, lon, reward, shopId, shopName,
         shopType, statusCode;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
