/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineJsonMap.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineJsonMap (0 custom class methods, 0 custom properties)

#import "GTLFlagengineJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineJsonMap
//

@implementation GTLFlagengineJsonMap
@end
