/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineLog.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineLog (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLFlagengineLog
//

@interface GTLFlagengineLog : GTLObject
@property (retain) NSNumber *category;  // longLongValue
@property (retain) NSNumber *createdAt;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *statusCode;  // intValue
@property (retain) NSNumber *subject;  // longLongValue
@property (retain) NSNumber *target;  // longLongValue
@property (retain) NSNumber *value;  // longLongValue
@end
