/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineLogCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineLogCollection (0 custom class methods, 1 custom properties)

#import "GTLFlagengineLogCollection.h"

#import "GTLFlagengineLog.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineLogCollection
//

@implementation GTLFlagengineLogCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLFlagengineLog class]
                                forKey:@"items"];
  return map;
}

@end
