/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API

#import "GTLFlagengineConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeFlagengineUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
