/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineProviderForm.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineProviderForm (0 custom class methods, 3 custom properties)

#import "GTLFlagengineProviderForm.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineProviderForm
//

@implementation GTLFlagengineProviderForm
@dynamic email, password, statusCode;
@end
