/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineFeedbackMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineFeedbackMessage (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLFlagengineText;

// ----------------------------------------------------------------------------
//
//   GTLFlagengineFeedbackMessage
//

@interface GTLFlagengineFeedbackMessage : GTLObject
@property (retain) NSNumber *createdAt;  // longLongValue
@property (copy) NSString *createdAtString;
@property (copy) NSString *email;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) GTLFlagengineText *message;
@property (retain) NSNumber *userId;  // longLongValue
@end
