/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineText.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineText (0 custom class methods, 1 custom properties)

#import "GTLFlagengineText.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineText
//

@implementation GTLFlagengineText
@dynamic value;
@end
