/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineUserInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineUserInfo (0 custom class methods, 6 custom properties)

#import "GTLFlagengineUserInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineUserInfo
//

@implementation GTLFlagengineUserInfo
@dynamic birth, job, lat, lon, sex, userId;
@end
