/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineRedeem.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineRedeem (0 custom class methods, 6 custom properties)

#import "GTLFlagengineRedeem.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineRedeem
//

@implementation GTLFlagengineRedeem
@dynamic identifier, imageUrl, name, price, statusCode, vendor;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
