/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineVersion.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineVersion (0 custom class methods, 3 custom properties)

#import "GTLFlagengineVersion.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineVersion
//

@implementation GTLFlagengineVersion
@dynamic createdAt, statusCode, version;
@end
