/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineShopCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineShopCollection (0 custom class methods, 1 custom properties)

#import "GTLFlagengineShopCollection.h"

#import "GTLFlagengineShop.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineShopCollection
//

@implementation GTLFlagengineShopCollection
@dynamic shops;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLFlagengineShop class]
                                forKey:@"shops"];
  return map;
}

@end
