/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineShop.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineShop (0 custom class methods, 13 custom properties)

#import "GTLFlagengineShop.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineShop
//

@implementation GTLFlagengineShop
@dynamic descriptionProperty, identifier, imageUrl, liked, likes, logoUrl, name,
         onSale, parentId, providerId, reward, rewarded, type;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"description", @"descriptionProperty",
      @"id", @"identifier",
      nil];
  return map;
}

@end
