/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineTOU.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineTOU (0 custom class methods, 2 custom properties)

#import "GTLFlagengineTOU.h"

#import "GTLFlagengineText.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineTOU
//

@implementation GTLFlagengineTOU
@dynamic identifier, tou;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
