/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineBeacon.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineBeacon (0 custom class methods, 7 custom properties)

#import "GTLFlagengineBeacon.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineBeacon
//

@implementation GTLFlagengineBeacon
@dynamic createdAt, flagId, identifier, lat, lon, name, shopId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
