/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineItemCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineItemCollection (0 custom class methods, 3 custom properties)

#import "GTLFlagengineItemCollection.h"

#import "GTLFlagengineItem.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineItemCollection
//

@implementation GTLFlagengineItemCollection
@dynamic hiddenItems, items, statusCode;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLFlagengineItem class], @"hiddenItems",
      [GTLFlagengineItem class], @"items",
      nil];
  return map;
}

@end
