/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineItemCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineItemCollection (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLFlagengineItem;

// ----------------------------------------------------------------------------
//
//   GTLFlagengineItemCollection
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLFlagengineItemCollection : GTLCollectionObject
@property (retain) NSArray *hiddenItems;  // of GTLFlagengineItem
@property (retain) NSArray *items;  // of GTLFlagengineItem
@property (retain) NSNumber *statusCode;  // intValue
@end
