/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineItem.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineItem (0 custom class methods, 17 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLFlagengineItem
//

@interface GTLFlagengineItem : GTLObject
@property (copy) NSString *barcodeId;

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (copy) NSString *descriptionProperty;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *liked;  // boolValue
@property (retain) NSNumber *likes;  // intValue
@property (copy) NSString *name;
@property (copy) NSString *oldPrice;
@property (copy) NSString *price;
@property (retain) NSNumber *reward;  // intValue
@property (retain) NSNumber *rewardable;  // boolValue
@property (retain) NSNumber *rewarded;  // boolValue
@property (retain) NSNumber *sale;  // intValue
@property (retain) NSNumber *sex;  // intValue
@property (retain) NSNumber *shopId;  // longLongValue
@property (retain) NSNumber *statusCode;  // intValue
@property (copy) NSString *thumbnailUrl;
@property (retain) NSNumber *type;  // intValue
@end
