/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineShop.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineShop (0 custom class methods, 14 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLFlagengineShop
//

@interface GTLFlagengineShop : GTLObject

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (copy) NSString *descriptionProperty;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *imageUrl;
@property (retain) NSNumber *liked;  // boolValue
@property (retain) NSNumber *likes;  // intValue
@property (copy) NSString *logoUrl;
@property (copy) NSString *name;
@property (retain) NSNumber *onSale;  // boolValue
@property (retain) NSNumber *parentId;  // longLongValue
@property (retain) NSNumber *providerId;  // longLongValue
@property (retain) NSNumber *reward;  // intValue
@property (retain) NSNumber *rewarded;  // boolValue
@property (retain) NSNumber *statusCode;  // intValue
@property (retain) NSNumber *type;  // intValue
@end
