/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineRetainForm.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineRetainForm (0 custom class methods, 2 custom properties)

#import "GTLFlagengineRetainForm.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineRetainForm
//

@implementation GTLFlagengineRetainForm
@dynamic identifier, statusCode;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
