/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineItemViewPair.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineItemViewPair (0 custom class methods, 5 custom properties)

#import "GTLFlagengineItemViewPair.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineItemViewPair
//

@implementation GTLFlagengineItemViewPair
@dynamic createdAt, identifier, nextId, preId, statusCode;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
