/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineShopCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineShopCollection (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLFlagengineFlag;
@class GTLFlagengineJsonMap;
@class GTLFlagengineShop;

// ----------------------------------------------------------------------------
//
//   GTLFlagengineShopCollection
//

@interface GTLFlagengineShopCollection : GTLObject
@property (retain) NSArray *flags;  // of GTLFlagengineFlag
@property (retain) GTLFlagengineJsonMap *pointMap;
@property (retain) NSArray *shops;  // of GTLFlagengineShop
@property (retain) NSNumber *statusCode;  // intValue
@end
