/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineRewardCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineRewardCollection (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLFlagengineReward;

// ----------------------------------------------------------------------------
//
//   GTLFlagengineRewardCollection
//

@interface GTLFlagengineRewardCollection : GTLObject
@property (retain) NSArray *rewards;  // of GTLFlagengineReward
@property (retain) NSNumber *statusCode;  // intValue
@end
