/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineNotice.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineNotice (0 custom class methods, 2 custom properties)

#import "GTLFlagengineNotice.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineNotice
//

@implementation GTLFlagengineNotice
@dynamic createdAt, message;
@end
