/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLFlagengineItem.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLFlagengineItem (0 custom class methods, 16 custom properties)

#import "GTLFlagengineItem.h"

// ----------------------------------------------------------------------------
//
//   GTLFlagengineItem
//

@implementation GTLFlagengineItem
@dynamic barcodeId, descriptionProperty, identifier, liked, likes, name,
         oldPrice, price, reward, rewardable, rewarded, sale, sex, shopId,
         thumbnailUrl, type;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"description", @"descriptionProperty",
      @"id", @"identifier",
      nil];
  return map;
}

@end
