/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryFlagengine.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   flagengine/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryFlagengine (68 custom class methods, 39 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLFlagengineBranchItemMatcher;
@class GTLFlagengineFeedbackMessage;
@class GTLFlagengineFlag;
@class GTLFlagengineIdString;
@class GTLFlagengineItem;
@class GTLFlagengineItemViewPair;
@class GTLFlagengineLike;
@class GTLFlagengineLog;
@class GTLFlagengineNotice;
@class GTLFlagenginePP;
@class GTLFlagengineProviderForm;
@class GTLFlagengineRedeem;
@class GTLFlagengineRetainForm;
@class GTLFlagengineReward;
@class GTLFlagengineShop;
@class GTLFlagengineTOU;
@class GTLFlagengineUserForm;
@class GTLFlagengineUserInfo;
@class GTLFlagengineVersion;

@interface GTLQueryFlagengine : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *barcodeId;
@property (assign) long long birth;
// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (copy) NSString *descriptionProperty;
@property (assign) BOOL empty;
@property (assign) long long end;
@property (assign) long long flagId;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
// "identifier" has different types for some query methods; see the
// documentation for the right type for each query method.
@property (retain) id identifier;
@property (retain) NSArray *ids;  // of NSNumber (longLongValue)
@property (copy) NSString *imageUrl;
@property (assign) long long itemId;
@property (assign) NSInteger job;
@property (assign) double lat;
@property (assign) BOOL liked;
@property (assign) NSInteger likes;
@property (copy) NSString *logoUrl;
@property (assign) double lon;
@property (assign) NSInteger mark;
@property (copy) NSString *name;
@property (copy) NSString *oldPrice;
@property (assign) BOOL onSale;
@property (assign) long long parentId;
@property (copy) NSString *phone;
@property (copy) NSString *price;
@property (assign) long long providerId;
@property (assign) double range;
@property (assign) NSInteger reward;
@property (assign) BOOL rewardable;
@property (assign) BOOL rewarded;
@property (assign) NSInteger sale;
@property (assign) NSInteger sex;
@property (assign) long long shopId;
@property (assign) long long start;
@property (assign) NSInteger statusCode;
@property (assign) long long tag;
@property (copy) NSString *thumbnailUrl;
@property (assign) NSInteger type;
@property (assign) long long userId;
@property (copy) NSString *verificationCode;

#pragma mark -
#pragma mark "apps.feedbacks" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.apps.feedbacks.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
+ (id)queryForAppsFeedbacksInsertWithObject:(GTLFlagengineFeedbackMessage *)object;

#pragma mark -
#pragma mark "apps.idstrings" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.apps.idstrings.delete
//  Optional:
//   identifier: For this method, "identifier" should be of type NSInteger.
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
+ (id)queryForAppsIdstringsDelete;

// Method: flagengine.apps.idstrings.get
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineIdStringCollection.
+ (id)queryForAppsIdstringsGet;

// Method: flagengine.apps.idstrings.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineIdString.
+ (id)queryForAppsIdstringsInsertWithObject:(GTLFlagengineIdString *)object;

#pragma mark -
#pragma mark "apps.notices" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.apps.notices.get
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineNotice.
+ (id)queryForAppsNoticesGet;

// Method: flagengine.apps.notices.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineNotice.
+ (id)queryForAppsNoticesInsertWithObject:(GTLFlagengineNotice *)object;

#pragma mark -
#pragma mark "apps.pps" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.apps.pps.get
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagenginePP.
+ (id)queryForAppsPpsGet;

// Method: flagengine.apps.pps.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagenginePP.
+ (id)queryForAppsPpsInsertWithObject:(GTLFlagenginePP *)object;

#pragma mark -
#pragma mark "apps.tous" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.apps.tous.get
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineTOU.
+ (id)queryForAppsTousGet;

// Method: flagengine.apps.tous.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineTOU.
+ (id)queryForAppsTousInsertWithObject:(GTLFlagengineTOU *)object;

#pragma mark -
#pragma mark "apps.versions" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.apps.versions.get
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineVersion.
+ (id)queryForAppsVersionsGet;

// Method: flagengine.apps.versions.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineVersion.
+ (id)queryForAppsVersionsInsertWithObject:(GTLFlagengineVersion *)object;

#pragma mark -
#pragma mark "flags" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.flags.delete
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
+ (id)queryForFlagsDeleteWithFlagId:(long long)flagId;

// Method: flagengine.flags.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineFlag.
+ (id)queryForFlagsInsertWithObject:(GTLFlagengineFlag *)object;

#pragma mark -
#pragma mark "flags.list" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.flags.list.all
//  Optional:
//   tag: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineFlagCollection.
+ (id)queryForFlagsListAll;

// Method: flagengine.flags.list.byitem
//  Optional:
//   itemId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineFlagCollection.
+ (id)queryForFlagsListByitem;

#pragma mark -
#pragma mark "flags.list.byitem" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.flags.list.byitem.reward
//  Optional:
//   itemId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineFlagCollection.
+ (id)queryForFlagsListByitemReward;

#pragma mark -
#pragma mark "flags.list" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.flags.list.byreward
//  Optional:
//   lat: double
//   lon: double
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineFlagCollection.
+ (id)queryForFlagsListByreward;

// Method: flagengine.flags.list.byshop
//  Optional:
//   shopId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineFlagCollection.
+ (id)queryForFlagsListByshop;

// Method: flagengine.flags.list.near
//  Optional:
//   lat: double
//   lon: double
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineFlagCollection.
+ (id)queryForFlagsListNear;

// Method: flagengine.flags.list.range
//  Optional:
//   lat: double
//   lon: double
//   range: double
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineFlagCollection.
+ (id)queryForFlagsListRange;

#pragma mark -
#pragma mark "images.uploadUrl" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.images.uploadUrl.get
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUploadUrl.
+ (id)queryForImagesUploadUrlGet;

#pragma mark -
#pragma mark "items.branch" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.items.branch.expose
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineBranchItemMatcher.
+ (id)queryForItemsBranchExposeWithObject:(GTLFlagengineBranchItemMatcher *)object;

// Method: flagengine.items.branch.hide
//  Optional:
//   itemId: long long
//   shopId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
+ (id)queryForItemsBranchHide;

// Method: flagengine.items.branch.reward
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineBranchItemMatcher.
+ (id)queryForItemsBranchRewardWithObject:(GTLFlagengineBranchItemMatcher *)object;

#pragma mark -
#pragma mark "items" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.items.delete
//  Optional:
//   itemId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
+ (id)queryForItemsDelete;

// Method: flagengine.items.get
//  Optional:
//   itemId: long long
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItem.
+ (id)queryForItemsGet;

// Method: flagengine.items.init
//  Optional:
//   mark: NSInteger
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItemCollection.
+ (id)queryForItemsInit;

// Method: flagengine.items.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItem.
+ (id)queryForItemsInsertWithObject:(GTLFlagengineItem *)object;

// Method: flagengine.items.list
//  Optional:
//   shopId: long long
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItemCollection.
+ (id)queryForItemsList;

#pragma mark -
#pragma mark "items.list" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.items.list.ids
//  Optional:
//   ids: NSArray
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItemCollection.
+ (id)queryForItemsListIds;

// Method: flagengine.items.list.item
//  Optional:
//   itemId: long long
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItemCollection.
+ (id)queryForItemsListItem;

// Method: flagengine.items.list.manager
//  Optional:
//   shopId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItemCollection.
+ (id)queryForItemsListManager;

// Method: flagengine.items.list.reward
//  Optional:
//   mark: NSInteger
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItemCollection.
+ (id)queryForItemsListReward;

// Method: flagengine.items.list.user
//  Optional:
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItemCollection.
+ (id)queryForItemsListUser;

#pragma mark -
#pragma mark "items" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.items.patch
//  Optional:
//   barcodeId: NSString
//   descriptionProperty: NSString
//   identifier: For this method, "identifier" should be of type long long.
//   liked: BOOL
//   likes: NSInteger
//   name: NSString
//   oldPrice: NSString
//   price: NSString
//   reward: NSInteger
//   rewardable: BOOL
//   rewarded: BOOL
//   sale: NSInteger
//   sex: NSInteger
//   shopId: long long
//   statusCode: NSInteger
//   thumbnailUrl: NSString
//   type: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItem.
+ (id)queryForItemsPatch;

// Method: flagengine.items.update
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItem.
+ (id)queryForItemsUpdateWithObject:(GTLFlagengineItem *)object;

#pragma mark -
#pragma mark "likes" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.likes.delete
//  Optional:
//   itemId: long long
//   type: NSInteger
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
+ (id)queryForLikesDelete;

// Method: flagengine.likes.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineLike.
+ (id)queryForLikesInsertWithObject:(GTLFlagengineLike *)object;

#pragma mark -
#pragma mark "logs" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.logs.get
//  Optional:
//   end: long long
//   start: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineLogCollection.
+ (id)queryForLogsGet;

// Method: flagengine.logs.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineLog.
+ (id)queryForLogsInsertWithObject:(GTLFlagengineLog *)object;

#pragma mark -
#pragma mark "logs.insert" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.logs.insert.ivpair
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineItemViewPair.
+ (id)queryForLogsInsertIvpairWithObject:(GTLFlagengineItemViewPair *)object;

#pragma mark -
#pragma mark "providers" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.providers.get
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineProvider.
+ (id)queryForProvidersGetWithObject:(GTLFlagengineProviderForm *)object;

// Method: flagengine.providers.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineProvider.
+ (id)queryForProvidersInsertWithObject:(GTLFlagengineProviderForm *)object;

#pragma mark -
#pragma mark "redeems" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.redeems.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineRedeem.
+ (id)queryForRedeemsInsertWithObject:(GTLFlagengineRedeem *)object;

// Method: flagengine.redeems.list
//  Optional:
//   mark: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineRedeemCollection.
+ (id)queryForRedeemsList;

#pragma mark -
#pragma mark "rewards" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.rewards.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUser.
+ (id)queryForRewardsInsertWithObject:(GTLFlagengineReward *)object;

// Method: flagengine.rewards.list
//  Optional:
//   mark: NSInteger
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineRewardCollection.
+ (id)queryForRewardsList;

#pragma mark -
#pragma mark "shops" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.shops.delete
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
+ (id)queryForShopsDeleteWithShopId:(long long)shopId;

// Method: flagengine.shops.get
//  Optional:
//   identifier: For this method, "identifier" should be of type long long.
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShop.
+ (id)queryForShopsGet;

// Method: flagengine.shops.init
//  Optional:
//   lat: double
//   lon: double
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShopCollection.
+ (id)queryForShopsInit;

// Method: flagengine.shops.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShop.
+ (id)queryForShopsInsertWithObject:(GTLFlagengineShop *)object;

// Method: flagengine.shops.list
//  Optional:
//   ids: NSArray
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShopCollection.
+ (id)queryForShopsList;

#pragma mark -
#pragma mark "shops.list" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.shops.list.provider
//  Optional:
//   providerId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShopCollection.
+ (id)queryForShopsListProvider;

// Method: flagengine.shops.list.reward
//  Optional:
//   mark: NSInteger
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShopCollection.
+ (id)queryForShopsListReward;

#pragma mark -
#pragma mark "shops" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.shops.patch
//  Optional:
//   descriptionProperty: NSString
//   identifier: For this method, "identifier" should be of type long long.
//   imageUrl: NSString
//   liked: BOOL
//   likes: NSInteger
//   logoUrl: NSString
//   name: NSString
//   onSale: BOOL
//   parentId: long long
//   providerId: long long
//   reward: NSInteger
//   rewarded: BOOL
//   statusCode: NSInteger
//   type: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShop.
+ (id)queryForShopsPatch;

#pragma mark -
#pragma mark "shops.recommend" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.shops.recommend.near
//  Optional:
//   ids: NSArray
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShop.
+ (id)queryForShopsRecommendNear;

#pragma mark -
#pragma mark "shops" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.shops.start
//  Optional:
//   mark: NSInteger
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShopCollection.
+ (id)queryForShopsStart;

// Method: flagengine.shops.update
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineShop.
+ (id)queryForShopsUpdateWithObject:(GTLFlagengineShop *)object;

#pragma mark -
#pragma mark "userinfos" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.userinfos.get
//  Optional:
//   userId: long long
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUserInfo.
+ (id)queryForUserinfosGet;

#pragma mark -
#pragma mark "userInfos" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.userInfos.patch
//  Optional:
//   birth: long long
//   empty: BOOL
//   job: NSInteger
//   phone: NSString
//   sex: NSInteger
//   statusCode: NSInteger
//   userId: long long
//   verificationCode: NSString
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUserInfo.
+ (id)queryForUserInfosPatch;

#pragma mark -
#pragma mark "userinfos.phone" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.userinfos.phone.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUserInfo.
+ (id)queryForUserinfosPhoneInsertWithObject:(GTLFlagengineUserInfo *)object;

// Method: flagengine.userinfos.phone.test
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUserInfo.
+ (id)queryForUserinfosPhoneTestWithObject:(GTLFlagengineUserInfo *)object;

#pragma mark -
#pragma mark "userInfos" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.userInfos.update
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUserInfo.
+ (id)queryForUserInfosUpdateWithObject:(GTLFlagengineUserInfo *)object;

#pragma mark -
#pragma mark "users" methods
// These create a GTLQueryFlagengine object.

// Method: flagengine.users.get
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUser.
+ (id)queryForUsersGetWithObject:(GTLFlagengineUserForm *)object;

// Method: flagengine.users.guest
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUser.
+ (id)queryForUsersGuest;

// Method: flagengine.users.insert
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUser.
+ (id)queryForUsersInsertWithObject:(GTLFlagengineUserForm *)object;

// Method: flagengine.users.retain
//  Authorization scope(s):
//   kGTLAuthScopeFlagengineUserinfoEmail
// Fetches a GTLFlagengineUser.
+ (id)queryForUsersRetainWithObject:(GTLFlagengineRetainForm *)object;

@end
